version: '3'

services:
  backend:

    container_name: backend

    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
      args:
        DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
        DJANGO_DEBUG: $DJANGO_DEBUG
        DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
        CORS_ALLOWED_ORIGINS: $CORS_ALLOWED_ORIGINS
        CSRF_TRUSTED_ORIGINS: $CSRF_TRUSTED_ORIGINS
        PROJECT_STAGE: $PROJECT_STAGE

    ports:
      - "8000:8000"

    volumes:
      - static_folder:/backend/static
      - media_folder:/backend/media


  frontend:

    container_name: frontend

    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
      args:
        API_HOST_URL: api

    volumes:
      - build_folder:/frontend/dist

  nginx:

    image: nginx:latest

    container_name: webserver

    ports:
      - "80:8080"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend
      - static_folder:/var/www/backend/static
      - media_folder:/var/www/backend/media

    depends_on:
    - backend
    - frontend

volumes:
  build_folder:
    name: "frontend"
  static_folder:
    name: "static-folder"
  media_folder:
    name: "media-folder"
