version: '3'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
      args:
        DJANGO_ALLOWED_HOSTS: api localhost 127.0.0.1 0.0.0.0 fracat-think.local fra-srv.mywire.org
        DJANGO_SECRET_KEY: 'django-insecure-ph%2qhc_!-qvc2w1@q9wz3(cd=jw$$mj1-x)o5#e$$a@h^l5zygg'
        DJANGO_DEBUG: 0
        CORS_ALLOWED_ORIGINS: http://localhost:5173 http://localhost:8000 http://api http://fracat-think.local http://fra-srv.mywire.org
        CSRF_TRUSTED_ORIGINS: http://localhost:5173 http://localhost:8000 http://api http://fracat-think.local http://fra-srv.mywire.org
    command: gunicorn backend.wsgi --bind 0.0.0.0:8000
    ports: 
      - "8000:8000"
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
      args:
        API_HOST_URL: api
    volumes:
      - build_folder:/frontend/dist
  nginx:
    image: nginx:latest
    container_name: webserver
    ports:
      - "80:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend
    depends_on:
    - backend
    - frontend

volumes:
  build_folder:
