version: '3'

services:
  backend:
    container_name: backend

    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
      args:
        DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
        DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE

    ports:
      - "8000:8000"

    volumes:
      - static_folder:/backend/static
      - media_folder:/backend/media


  frontend:
    container_name: frontend

    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
      args:
        API_HOST_URL: api

    volumes:
      - build_folder:/frontend/dist

  nginx:
    image: nginx:latest
    container_name: webserver
    ports:
      - "80:8080"
      - "443:443"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend
      - static_folder:/var/www/backend/static
      - media_folder:/var/www/backend/media
      - ./certs:/certs

    depends_on:
    - backend
    - frontend


volumes:
  build_folder:
    name: "frontend"
  static_folder:
    name: "static-folder"
  media_folder:
    name: "media-folder"
