name: Frontend CI

on: [push]

jobs:
  dive:
    runs-on: ubuntu-latest
    name: Analyze image efficiency
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build ./frontend --file docker/frontend/Dockerfile --tag frontend:$(date +%s)
      - name: Dive
        uses: yuichielectric/dive-action@0.0.4
        with:
          image: "frontend:$(date +%s)"
          config-file: ${{ github.workspace }}/.dive-ci.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}