name: Frontend CI

on: [push]

jobs:
  dive:
    name: Test Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build ./frontend --file docker/frontend/Dockerfile --tag frontend:ci_build

      - name: Run Dive Image Check
        uses: yuichielectric/dive-action@0.0.4
        with:
          image: frontend:ci_build
          config-file: ${{ github.workspace }}/.dive-ci.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: frontend:ci_build
          trivy-config: trivy.yaml