name: Frontend CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "Build and Test Frontend Image"
        run: docker build ./frontend --file docker/frontend/Dockerfile --tag frontend:$(date +%s)
          docker pull wagoodman/dive
          docker run --rm -ti \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "./.dive-ci":"/.dive-ci" \
            wagoodman/dive:latest --ci frontend:$(date +%s)